version: '2.4'

services:
  app:
    image: node:12.17.0-alpine3.11
    command: npm run start:dev
    volumes:
      - './app:/app'
    working_dir: /app
    user: node
    ports:
      - "3000:3000"
    env_file: 
        - .env
  
  mysql:
    image: mysql:5
    restart: on-failure
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - '3306:3306'
