version: '2.4'

services:
  app:
    image: node:12.17.0-alpine3.11
    command: npm run start:dev
    volumes:
      - './app:/app'
    working_dir: /app
    user: node
    ports:
      - "3000:3000"
      
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080

  mysql:
    image: mysql:5
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 'PYm[fkUfPSn<P6K%'
      MYSQL_DATABASE: 'pokemon'
    ports:
      - '3306:3306'
